#!/usr/bin/env bash

# ------------------------
# Tropicloud WP-STACK
# ------------------------
# @author: Guigo (guigo.pw)
# version: 0.2
# ------------------------

wps='/usr/local/wps' && home='/var/www/wps'

# ------------------------
# WP-STACK Functions
# ------------------------

for f in $wps/bin/*.sh; do . $f; done

  if [[  $1 == 'setup'  ]];   then wps_setup
elif [[  $1 == 'start'  ]];   then wps_start $@
elif [[  $1 == 'stop'  ]];    then wps_start $@
elif [[  $1 == 'restart'  ]]; then wps_start $@
elif [[  $1 == 'login'  ]];   then wps_login $@

# ------------------------
# WP-STACK Commands
# ------------------------

else echo "
----------------------------------------------------
  WP-STACK  - www.tropicloud.net
----------------------------------------------------  

  HOW TO USE:
  
----------------------------------------------------  

"
fi
