#!/usr/bin/env bash

# ------------------------
# Tropicloud WP-STACK
# ------------------------
# @author: Guigo (guigo.pw)
# version: 0.2
# ------------------------

wps='/usr/local/wps' && home='/var/www/wps'

# ------------------------
# WP-STACK Functions
# ------------------------

for f in $wps/bin/*.sh; do . $f; done

  if [[  $1 == 'setup'  ]];   then wps_setup

elif [[  $1 == 'start'  ]];   then wps_start $@
elif [[  $1 == 'stop'  ]];    then wps_stop $@
elif [[  $1 == 'restart'  ]]; then wps_restart $@
elif [[  $1 == 'import'  ]];  then wps_import $@
elif [[  $1 == 'export'  ]];  then wps_export $@
elif [[  $1 == 'usradd'  ]];  then wps_usradd $@
elif [[  $1 == 'usrdel'  ]];  then wps_usrdel $@
elif [[  $1 == 'pwd'  ]];     then wps_pwd $@
elif [[  $1 == 'plugin'  ]];  then wps_plugin $@

# ------------------------
# WP-STACK Commands
# ------------------------

else echo "
----------------------------------------------------
  WP-STACK  - www.tropicloud.net
----------------------------------------------------  

  HOW TO USE:
  
----------------------------------------------------  

"
fi
